# $NetBSD: Makefile.common,v 1.31 2012/12/07 10:06:13 adam Exp $
# used by wip/qt4-libs/Makefile.common
# used by wip/qt4-tools/Makefile

QTVERSION=	4.8.5

MAINTAINER?=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://qt-project.org/

LICENSE=	gnu-lgpl-v2.1 AND gnu-gpl-v3
